---
title: "Test"
author: "Jess"
date: "9/17/2020"
output: html_document
---

```{r}
#source("C:/Users/iamje/Jess/UNSW/BEES0006/specieshindex/R/Hindex.r") #load specieshindex functions
library(taxize)
library(httr)
library(XML)
library(rscopus)
library(specieshindex)

taxonomy <- read.csv(file = "Datasets/taxonomy.csv", header = T)
```

```{r}
DownloadAll <- function(data) {
  totalspp <- nrow(data)
  APIkey <- "442b9048417ef20cf680a0ae26ee4d86"
  datalist = list()
  print("Starting loop now.")
  for (i in 1:totalspp) {
    print(i)
    species <- FetchSpTAK(data$genusName[i],
                          data$speciesName[i], 
                          APIkey)
    sppindex <- Allindices(species, genus = data$genusName[i], species = data$speciesName[i])
    print(paste(length(species), "records retrieved."))
    datalist[[i]] <- sppindex
  }
  return(datalist)
}
```

```{r}
marsupials <- DownloadAll(taxonomy)
marsupial_df<-bind_rows(marsupials)

CountSpTAK("Spilocuscus", "rufoniger", "442b9048417ef20cf680a0ae26ee4d86") #0
Ailurops_melanotis <- FetchSpTAK("Ailurops", "melanotis", "442b9048417ef20cf680a0ae26ee4d86")
Myrmecobius_fasciatus <- FetchSpTAK("Myrmecobius", "fasciatus", "442b9048417ef20cf680a0ae26ee4d86")

Allindex <- Allindices(Myrmecobius_fasciatus, genus = "Myrmecobius", species = "fasciatus")

noCitations <- data.frame(citations = 0, journals = 0)
```


