library(formattable)

includeh <- read.csv(file = "outputs/data/includeh.csv")[-c(1)] 

table_df <- data.frame("Predictor" = c("Body mass",
                                       "Latitude",
                                       "Phylogeny",
                                       "Phylogenetic tree",
                                       "IUCN Red List status",
                                       "Human use",
                                       "Domestication",
                                       "Google trends"),
                       "Completeness" = c(paste0(round(5158/7522*100, digits = 1), "%"),
                                          paste0(round(4435/7522*100, digits = 1), "%"),
                                          paste0(round(6549/7522*100, digits = 1), "%"),
                                          paste0(round(5498/7522*100, digits = 1), "%"),
                                          paste0(round(5244/7522*100, digits = 1), "%"),
                                          paste0(round(1397/7522*100, digits = 1), "%"),
                                          paste0(round(7522/7522*100, digits = 1), "%"),
                                          paste0(round(1323/7522*100, digits = 1), "%")),
                       "Treatment" = c("Log transformation",
                                       "/",
                                       "/",
                                       "/",
                                       "Converted to ordinal",
                                       "Converted to binomial",
                                       "Converted to ordinal",
                                       "Converted to binomial"),
                       "Treatment details" = c("log10(value)",
                                               "/",
                                               "/",
                                               "/",
                                               "1 = LC; 2 = VU; 3 = EN; 4 = CE; 5 = EW",
                                               "0 = data present; 1 = data absent",
                                               "1 = Domesticated; 2 = Partially-domesticated; 3 = Wild",
                                               "0 = 0; 1 = not 0"),
                       "Require imputation" = c("Yes",
                                                "Yes",
                                                "No",
                                                "No",
                                                "Yes",
                                                "No",
                                                "No",
                                                "No"))

formattable(table_df,
            align = c("l"),
            list("Completeness" = color_bar("#71CA97"),
                 area(col = 2) ~ color_tile("#B1CBEB", "#3E7DCC"),
                 "Require imputation" = formatter(icontext(c("Yes", "Yes", "No", "No", "Yes", "No", "No", "No")),
                                                  style = x ~ style(color = "red", "green"))))
