library(ggplot2)

themebyjess_light_point <- function() {
  theme(axis.title = element_text(family = "Lato",
                                  face = "bold",
                                  size = 14,
                                  colour = "black"),
        axis.text = element_text(family = "Lato",
                                 size = 10,
                                 colour = "grey20"),
        axis.line = element_line(size = 1.05,
                                 colour = "grey20"),
        legend.background = element_rect(fill = "#163548"),
        legend.title = element_blank(),
        legend.text = element_text(family = "Roboto",
                                   size = 14,
                                   colour = "black"),
        legend.key = element_rect(fill = "white"),
        legend.position = "top",
        legend.justification = "centre",
        plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "grey50"),
        panel.grid.minor = element_line(colour = "grey50",
                                        linetype = "longdash"))
}

themebyjess_light_boxplot <- function() {
  theme(axis.title.x = element_text(family = "Lato",
                                    face = "bold",
                                    size = 14,
                                    colour = "black"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(family = "Lato",
                                   size = 10,
                                   colour = "grey20"),
        axis.text.y = element_text(family = "Lato",
                                   size = 14,
                                   colour = "black"),
        axis.line = element_line(size = 1.05,
                                 colour = "grey20"),
        legend.background = element_rect(fill = "white"),
        legend.title = element_blank(),
        legend.text = element_text(family = "Roboto",
                                   size = 14,
                                   colour = "black"),
        legend.key = element_rect(fill = "white"),
        legend.position = "top",
        legend.justification = "centre",
        plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major.x = element_line(colour = "grey50"),
        panel.grid.minor.x = element_line(colour = "grey50",
                                          linetype = "longdash"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())
}

themebyjess_light_map <- function() {
  theme(axis.title = element_text(family = "Lato",
                                  face = "bold",
                                  size = 14,
                                  colour = "black"),
        axis.text = element_text(family = "Lato",
                                 size = 10,
                                 colour = "grey20"),
        axis.line = element_line(size = 1.05,
                                 colour = "grey20"),
        legend.background = element_rect(fill = "white"),
        legend.title = element_text(family = "Roboto",
                                    face = "bold",
                                    size = 14,
                                    colour = "black"),
        legend.text = element_text(family = "Roboto",
                                   size = 14,
                                   colour = "black"),
        legend.key = element_rect(fill = "white"),
        legend.position = "right",
        legend.justification = "centre",
        plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "grey50"),
        panel.grid.minor = element_line(colour = "grey50",
                                        linetype = "longdash"))
}

themebyjess_dark_point <- function() {
  theme(axis.title = element_text(family = "Lato",
                                  face = "bold",
                                  size = 14,
                                  colour = "white"),
        axis.text = element_text(family = "Lato",
                                 size = 10,
                                 colour = "grey80"),
        axis.line = element_line(size = 1.05,
                                 colour = "grey80"),
        legend.background = element_rect(fill = "#163548"),
        legend.title = element_blank(),
        legend.text = element_text(family = "Roboto",
                                   size = 14,
                                   colour = "white"),
        legend.key = element_rect(fill = "#163548"),
        legend.position = "top",
        legend.justification = "centre",
        plot.background = element_rect(fill = "#163548"),
        panel.background = element_rect(fill = "#163548"),
        panel.grid.major = element_line(colour = "grey50"),
        panel.grid.minor = element_line(colour = "grey50",
                                        linetype = "longdash"))
}

themebyjess_dark_boxplot <- function() {
  theme(axis.title.x = element_text(family = "Lato",
                                    face = "bold",
                                    size = 14,
                                    colour = "white"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(family = "Lato",
                                   size = 10,
                                   colour = "grey80"),
        axis.text.y = element_text(family = "Lato",
                                   size = 14,
                                   colour = "white"),
        axis.line = element_line(size = 1.05,
                                 colour = "grey80"),
        legend.background = element_rect(fill = "#163548"),
        legend.title = element_blank(),
        legend.text = element_text(family = "Roboto",
                                   size = 14,
                                   colour = "white"),
        legend.key = element_rect(fill = "#163548"),
        legend.position = "top",
        legend.justification = "centre",
        plot.background = element_rect(fill = "#163548"),
        panel.background = element_rect(fill = "#163548"),
        panel.grid.major.x = element_line(colour = "grey50"),
        panel.grid.minor.x = element_line(colour = "grey50",
                                          linetype = "longdash"),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())
}

themebyjess_dark_map <- function() {
  theme(axis.title = element_text(family = "Lato",
                                  face = "bold",
                                  size = 14,
                                  colour = "white"),
        axis.text = element_text(family = "Lato",
                                 size = 10,
                                 colour = "grey80"),
        axis.line = element_line(size = 1.05,
                                 colour = "grey80"),
        legend.background = element_rect(fill = "#163548"),
        legend.title = element_text(family = "Roboto",
                                    face = "bold",
                                    size = 14,
                                    colour = "white"),
        legend.text = element_text(family = "Roboto",
                                   size = 14,
                                   colour = "white"),
        legend.key = element_rect(fill = "#163548"),
        legend.position = "right",
        legend.justification = "centre",
        plot.background = element_rect(fill = "#163548"),
        panel.background = element_rect(fill = "#163548"),
        panel.grid.major = element_line(colour = "grey50"),
        panel.grid.minor = element_line(colour = "grey50",
                                        linetype = "longdash"))
}